# Importing Libararies

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing Dataset

In [ ]:
dataset = pd.read_csv("/content/SalaryData_Train.csv")

In [ ]:
dataset.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
dataset.education.unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' 7th-8th', ' Doctorate',
       ' Assoc-voc', ' Prof-school', ' 5th-6th', ' 10th', ' Preschool',
       ' 12th', ' 1st-4th'], dtype=object)

In [ ]:
dataset.educationno.unique()

array([13,  9,  7, 14,  5, 10, 12,  4, 16, 11, 15,  3,  6,  1,  8,  2])

In [ ]:
dataset.capitalgain.unique()

array([ 2174,     0, 14084,  5178,  5013,  2407, 14344, 15024,  7688,
        4064,  4386,  7298,  1409,  3674,  1055,  2050,  2176,   594,
       20051,  6849,  4101,  8614,  3411,  2597, 25236,  4650,  2463,
        3103, 10605,  2964,  3325,  2580,  3471,  4865, 99999,  6514,
        1471,  2329,  2105,  2885, 10520,  2202,  2961, 27828,  6767,
        2228,  1506, 13550,  2635,  5556,  4787,  3781,  3137,  3818,
         914,   401,  2829,  2977,  4934,  2062,  2354,  3464,  5455,
       15020,  1424,  3273, 22040,  4416, 10566,  4931,  7430, 34095,
        6497,  3908,   114,  2346,  2907,  1151,  9386,  2414,  2290,
        3418, 15831, 41310,  4508,  2538,  3456,  1848,  3887,  7896,
        5721,  9562,  6418,  1455,  2036,  3942,  1831, 11678,  2936,
        2993,  7443,  6360,  4687,  1797,  6723,  2009,  3432,  6097,
        1639,  2653, 18481, 25124,  7978,   991,  1173,  2387,  5060,
        1086])

In [ ]:
dataset.capitalloss.unique()

array([   0, 2042, 1408, 1902, 1887, 1719, 1762, 1564, 2179, 1816, 1980,
       1977, 1876, 1340, 2206, 1741, 1485, 2339, 2415, 1380, 1721, 2051,
       2377, 1669, 2352, 1672,  653, 2392, 1504, 1590, 1651, 1628, 1848,
       2001, 1740, 2002, 1579, 2258, 1602, 2547, 2205, 1726, 2444, 1138,
       2238,  625,  213, 1539,  880, 1668, 1092, 1594, 2231, 1844,  810,
       2824, 2559, 2057, 1573, 1974,  974, 2174, 2149, 1735, 1258, 2603,
       2282,  323, 2246, 1617, 1648, 1825, 3770, 1755, 3683, 2129, 4356,
       2267, 2080, 2457,  419,  155, 3900, 2201, 1944, 2467, 2754, 2472,
       3004, 1411])

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64
 10  capitalloss    30161 non-null  int64
 11  hoursperweek   30161 non-null  int64
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB

In [ ]:
dataset.shape

(30161, 14)

In [ ]:
dataset.drop_duplicates

<bound method DataFrame.drop_duplicates of        age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse
2       38            Private      HS-grad            9             Divorced
3       53            Private         11th            7   Married-civ-spouse
4       28            Private    Bachelors           13   Married-civ-spouse
...    ...                ...          ...          ...                  ...
30156   27            Private   Assoc-acdm           12   Married-civ-spouse
30157   40            Private      HS-grad            9   Married-civ-spouse
30158   58            Private      HS-grad            9              Widowed
30159   22            Private      HS-grad            9        Never-married
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174
1         Exec-managerial         Husband   White     Male            0
2       Handlers-cleaners   Not-in-family   White     Male            0
3       Handlers-cleaners         Husband   Black     Male            0
4          Prof-specialty            Wife   Black   Female            0
...                   ...             ...     ...      ...          ...
30156        Tech-support            Wife   White   Female            0
30157   Machine-op-inspct         Husband   White     Male            0
30158        Adm-clerical       Unmarried   White   Female            0
30159        Adm-clerical       Own-child   White     Male            0
30160     Exec-managerial            Wife   White   Female        15024

       capitalloss  hoursperweek          native  Salary
0                0            40   United-States   <=50K
1                0            13   United-States   <=50K
2                0            40   United-States   <=50K
3                0            40   United-States   <=50K
4                0            40            Cuba   <=50K
...            ...           ...             ...     ...
30156            0            38   United-States   <=50K
30157            0            40   United-States    >50K
30158            0            40   United-States   <=50K
30159            0            20   United-States   <=50K
30160            0            40   United-States    >50K

[30161 rows x 14 columns]>

In [ ]:
dataset.Salary.unique()

array([' <=50K', ' >50K'], dtype=object)

In [ ]:
dataset = dataset.replace(to_replace = " <=50K",value = 1)

In [ ]:
dataset = dataset.replace(to_replace = " >50K",value = 2)

In [ ]:
dataset

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,1
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,1
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,1
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,1
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30156,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,1
30157,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,2
30158,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,1
30159,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,1
30160,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,2

#dropping unnecessary features

In [ ]:
data = dataset.drop(columns = ['education', 'maritalstatus','relationship','race','sex','native'])

In [ ]:
data

,age,workclass,educationno,occupation,capitalgain,capitalloss,hoursperweek,Salary
0,39,State-gov,13,Adm-clerical,2174,0,40,1
1,50,Self-emp-not-inc,13,Exec-managerial,0,0,13,1
2,38,Private,9,Handlers-cleaners,0,0,40,1
3,53,Private,7,Handlers-cleaners,0,0,40,1
4,28,Private,13,Prof-specialty,0,0,40,1
...,...,...,...,...,...,...,...,...
30156,27,Private,12,Tech-support,0,0,38,1
30157,40,Private,9,Machine-op-inspct,0,0,40,2
30158,58,Private,9,Adm-clerical,0,0,40,1
30159,22,Private,9,Adm-clerical,0,0,20,1
30160,52,Self-emp-inc,9,Exec-managerial,15024,0,40,2

#ENCODING THE CATEGORICAL DATA

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['workclass']= label_encoder.fit_transform(data['workclass'])

In [ ]:
data['workclass'].unique()

array([5, 4, 2, 0, 1, 3, 6])

In [ ]:
data['occupation']= label_encoder.fit_transform(data['occupation'])
data['occupation'].unique()

array([ 0,  3,  5,  9,  7, 11, 13,  4,  6, 12,  2, 10,  1,  8])

# Independent and dependent Variables

In [ ]:
X = data.iloc[:, 0:7].values #X train values
y = data.iloc[:, 7].values # y train values

In [ ]:
X

array([[   39,     5,    13, ...,  2174,     0,    40],
       [   50,     4,    13, ...,     0,     0,    13],
       [   38,     2,     9, ...,     0,     0,    40],
       ...,
       [   58,     2,     9, ...,     0,     0,    40],
       [   22,     2,     9, ...,     0,     0,    20],
       [   52,     3,     9, ..., 15024,     0,    40]])

In [ ]:
y

array([1, 1, 1, ..., 1, 1, 2])

#TEST DATASET

In [ ]:
test = pd.read_csv("/content/SalaryData_Test.csv")

In [ ]:
test.shape

(15060, 14)

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            15060 non-null  int64
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64
 10  capitalloss    15060 non-null  int64
 11  hoursperweek   15060 non-null  int64
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB

In [ ]:
test1 = test.drop_duplicates()

In [ ]:
test1.shape

(14130, 14)

In [ ]:
test2 = test1.dropna()

In [ ]:
test2

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,Private,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K
15056,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K
15057,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
15058,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K
15059,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K

In [ ]:
test3 = test2.drop(columns = ['education', 'maritalstatus','relationship','race','sex','native'])

In [ ]:
test3

,age,workclass,educationno,occupation,capitalgain,capitalloss,hoursperweek,Salary
0,25,Private,7,Machine-op-inspct,0,0,40,<=50K
1,38,Private,9,Farming-fishing,0,0,50,<=50K
2,28,Local-gov,12,Protective-serv,0,0,40,>50K
3,44,Private,10,Machine-op-inspct,7688,0,40,>50K
4,34,Private,6,Other-service,0,0,30,<=50K
...,...,...,...,...,...,...,...,...
15055,33,Private,13,Prof-specialty,0,0,40,<=50K
15056,39,Private,13,Prof-specialty,0,0,36,<=50K
15057,38,Private,13,Prof-specialty,0,0,50,<=50K
15058,44,Private,13,Adm-clerical,5455,0,40,<=50K
15059,35,Self-emp-inc,13,Exec-managerial,0,0,60,>50K

In [ ]:
test3 = test3.replace(to_replace = " <=50K",value = 1)

In [ ]:
test3 = test3.replace(to_replace = " >50K",value = 2)

In [ ]:
test3

,age,workclass,educationno,occupation,capitalgain,capitalloss,hoursperweek,Salary
0,25,Private,7,Machine-op-inspct,0,0,40,1
1,38,Private,9,Farming-fishing,0,0,50,1
2,28,Local-gov,12,Protective-serv,0,0,40,2
3,44,Private,10,Machine-op-inspct,7688,0,40,2
4,34,Private,6,Other-service,0,0,30,1
...,...,...,...,...,...,...,...,...
15055,33,Private,13,Prof-specialty,0,0,40,1
15056,39,Private,13,Prof-specialty,0,0,36,1
15057,38,Private,13,Prof-specialty,0,0,50,1
15058,44,Private,13,Adm-clerical,5455,0,40,1
15059,35,Self-emp-inc,13,Exec-managerial,0,0,60,2

In [ ]:
label_encoder_test = preprocessing.LabelEncoder()
test3['workclass']= label_encoder_test.fit_transform(test3['workclass'])
test3['occupation']= label_encoder_test.fit_transform(test3['occupation'])

In [ ]:
test3

,age,workclass,educationno,occupation,capitalgain,capitalloss,hoursperweek,Salary
0,25,2,7,6,0,0,40,1
1,38,2,9,4,0,0,50,1
2,28,1,12,10,0,0,40,2
3,44,2,10,6,7688,0,40,2
4,34,2,6,7,0,0,30,1
...,...,...,...,...,...,...,...,...
15055,33,2,13,9,0,0,40,1
15056,39,2,13,9,0,0,36,1
15057,38,2,13,9,0,0,50,1
15058,44,2,13,0,5455,0,40,1
15059,35,3,13,3,0,0,60,2

In [ ]:
X_test =  test3.iloc[:, 0:7].values

In [ ]:
X_test

array([[  25,    2,    7, ...,    0,    0,   40],
       [  38,    2,    9, ...,    0,    0,   50],
       [  28,    1,   12, ...,    0,    0,   40],
       ...,
       [  38,    2,   13, ...,    0,    0,   50],
       [  44,    2,   13, ..., 5455,    0,   40],
       [  35,    3,   13, ...,    0,    0,   60]])

In [ ]:
y_test = test3.iloc[:,7].values

In [ ]:
y_test

array([1, 1, 2, ..., 1, 1, 2])

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X)
X_test = sc_X.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.04277892,  2.93594688,  1.12889813, ...,  0.14608503,
        -0.21850808, -0.07773541],
       [ 0.88026081,  1.88764517,  1.12889813, ..., -0.14744712,
        -0.21850808, -2.33149486],
       [-0.0333558 , -0.20895825, -0.4397325 , ..., -0.14744712,
        -0.21850808, -0.07773541],
       ...,
       [ 1.48933854, -0.20895825, -0.4397325 , ..., -0.14744712,
        -0.21850808, -0.07773541],
       [-1.25151126, -0.20895825, -0.4397325 , ..., -0.14744712,
        -0.21850808, -1.74718685],
       [ 1.03253024,  0.83934346, -0.4397325 , ...,  1.88108414,
        -0.21850808, -0.07773541]])

In [ ]:
X_test

array([[-1.05408752, -0.22877429, -1.19914608, ..., -0.15005852,
        -0.22610763, -0.08753833],
       [-0.08603828, -0.22877429, -0.43064399, ..., -0.15005852,
        -0.22610763,  0.72761694],
       [-0.83069154, -1.23706521,  0.72210915, ..., -0.15005852,
        -0.22610763, -0.08753833],
       ...,
       [-0.08603828, -0.22877429,  1.10636019, ..., -0.15005852,
        -0.22610763,  0.72761694],
       [ 0.36075367, -0.22877429,  1.10636019, ...,  0.54019335,
        -0.22610763, -0.08753833],
       [-0.30943426,  0.77951663,  1.10636019, ..., -0.15005852,
        -0.22610763,  1.54277221]])

#ML Algorithm

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([1, 1, 1, ..., 1, 2, 1])

In [ ]:
y_test

array([1, 1, 2, ..., 1, 1, 2])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)
print(cm)
print(acc)

[[10040   580]
 [ 2406  1104]]
0.7886765746638358

#DATA Visualization